### PR TITLE
fix for incompatible pointer type on kernels < 5.15

### PR DESCRIPTION
**Pull request by mdidomenico4**

### CODE REVIEW

**Comment by medusalix** [comment]
Thanks for the PR, but it fails to build for me on kernel 5.12:

```
make: Entering directory '/usr/src/kernels/5.12.8-300.fc34.x86_64'
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/bus.o
/var/lib/dkms/xone/unknown/build/bus/bus.c:126:19: error: initialization of ‘int (*)(struct device *)’ from incompatible pointer type ‘void (*)(struct device *)’ [-Werror=incompatible-pointer-types]
  126 |         .remove = gip_bus_remove_compat,
      |                   ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/xone/unknown/build/bus/bus.c:126:19: note: (near initialization for ‘gip_bus_type.remove’)
```

I think this solution might be better: dlundqvist/xone#5

**Comment by medusalix** [comment]
I just tried the PR I've linked and it also doesn't work for me. Are you sure you're using the correct kernel headers for your kernel version? I've tried the latest `master` with kernel 5.11, 5.12, 5.13, 5.14 and 5.15 and it works for all versions.

**Comment by mdidomenico4** [comment]
i'm definitely using the right kernel headers.  i might be that you're testing on Fedora and I'm using Rocky Linux

**Comment by medusalix** [comment]
I actually tested the kernel versions on Arch Linux. But now that you've mentioned it I've looked into the Rocky Linux kernel sources and it seems like they include certain commits from newer kernels in their 5.14 package. The `bus_type.remove` function signature change was done in 5.15 but Rocky Linux decided to port this to 5.14. That's why the version check fails in `xone`. Unfortunately there's not much we can do about that without breaking `xone` for other distros.

**Pull request closed without merging**
