### PR TITLE
Add unknown vendor ID

### PR DESCRIPTION
**Pull request by Iamnotagenius**

### CODE REVIEW

**Comment by slmb3** [comment]
why changed LSI Corporation vendor ID to unknown vendor ID?

**Comment by medusalix** [comment]
Because there's no reason to assume that the gamepad is from LSI Corporation. They have the **PCI** vendor ID `0x11c1` but their USB vendor ID is completely different.

The only match you get when you search for the USB vendor ID `0x11c1` is *Wako Giken Kogyo Co., Ltd.* which doesn't seem to develop any Xbox accessories.

**Comment by YogSottot** [comment]
I have this controller
```ID 11c1:2001```

But the ```share``` button presses are not detected in ```evtest```
All other buttons and sticks work normally.
Is there anything I can do about it?

**Comment by medusalix** [comment]
Please give the `share-button` branch a try.

**Comment by YogSottot** [comment]
> Please give the `share-button` branch a try.

Installed the driver from this branch. Now the share button is detected. Thank you very much.

```
Event: time 1705157758.461637, type 1 (EV_KEY), code 167 (KEY_RECORD), value 1
Event: time 1705157758.461637, -------------- SYN_REPORT ------------
Event: time 1705157758.673659, type 1 (EV_KEY), code 167 (KEY_RECORD), value 0
Event: time 1705157758.673659, -------------- SYN_REPORT 
```

**Pull request merged**
