### PR TITLE
Feature Request: Xbox 360 Support

### PR DESCRIPTION
**Pull request by trymeouteh**
There is no issue or discussion tab on this github project and I do not have discord and will not use discord due to their privacy policy. Sorry for opening a pull request but this is the only way I can make a feature request.

Please add support for Xbox 360 controllers and headsets to replace xpad completely.

### CODE REVIEW

**Comment by medusalix** [comment]
I'm sorry but I don't have any plans to implement support for Xbox 360 accessories right now. The Xbox 360 controllers use a completely different protocol and that would require a separate driver module in any case. I don't have any Xbox 360 controllers and I'd like to keep the focus on newer hardware for `xone`.
The goal is to submit `xone` for the mainline Linux kernel tree, which would move the Xbox One functionality from `xpad` to `xone` while keeping the Xbox 360 support in the `xpad` module.

**Comment by trymeouteh** [comment]
If this can get into the kernal and therefore xbox 360, xbox one and the newer x series controllers work on linux and the xone will not conflict with xpad drivers for xbox 360 controllers, that would be excellent.

**Comment by TobiPeterG** [comment]
Are there any news on that?
I would like to use an xbox 360 controller and my xbox one controller on my pc, but I have to choose currently.
Is it safe to use the xpad driver next to xow?

**Comment by mkopec** [comment]
@TobiPeterG Check out the [xpad-noone](https://github.com/medusalix/xpad-noone) driver from the same developer, it's just xpad with Xbox One controller support removed so it doesn't conflict with xone.

**Pull request closed without merging**
